# flow_cytometry/environment.yml
name: fcs-demo
channels: [conda-forge]
dependencies:
  - python=3.11
  - pandas>=2.2
  - numpy
  - matplotlib
  - ipykernel
  - pip
  - nbconvert         # for the pre-commit hook
  - jupyter_client    # nbconvert runtime dep
  - pip:
      - readfcs
      - flowkit
      - fcsparser
      - scipy
      - umap-learn
